version: '3.1'
name: Hospital-Side-Selection
services:
  hospital-api:
    container_name: backend
    build: .
    restart: on-failure
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://postgres:postgres@postgres:5432/db
      NODE_ENV: development
      PORT: 3001
    ports:
      - "3001:3001"
    volumes:
      - ./:/app
      - /app/node_modules
  db:
    container_name: postgresql_db
    image: postgis/postgis
    # automatically restarts the container - Docker daemon on restart or 
    # the container itself is manually restarted
    restart: always 

    volumes:
      - ./data/db:/var/lib/postgresql/data
      - ./backup:/dc

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "8000:5432"
    # networks:
    #   app_net:
    #     ipv4_address: 192.168.0.2  

  pgadmin:
    container_name: pgadmin4
    image: dpage/pgadmin4
    restart: always

    volumes:
      - ./data/pgadmin-data:/var/lib/pgadmin

    environment:
      PGADMIN_DEFAULT_EMAIL: root@root.com
      PGADMIN_DEFAULT_PASSWORD: root
      # PGADMIN_LISTEN_PORT = 80
    ports:
      - "5050:80"
    # networks:
    #   app_net:
    #     ipv4_address: 192.168.0.3
  nginx:
    container_name: local-nginx
    build: ./nginx
    volumes:
      - ./nginx/html:/usr/share/nginx/html
      - ./nginx/conf.d:/etc/nginx/conf.d
    ports:
      - "80:80"
      - "443:443"
    restart: "always"
  frontend:
    container_name: react-app
    build: ../hospital-side-selection
    volumes:
      - ../hospital-side-selection:/frontend
      - /frontend/node_modules
    ports:
      - "3000:3000"

    
# networks:
#   app_net:
#     ipam:
#       driver: default
#       config:
#         - subnet: "192.168.0.0/24"
#           gateway: 192.168.0.1